List of possible statistical tests:

  - I could calculate the central tendencies of the dataset and z-scores for every decade or year from 1921=2020 based on song duration or other qualities included in the dataset. This would allow me to compare which decade/year had the longest songs and how song duration has changed by observing how z-scores have changed
  - Visualization, such as a line graph, would be helpful for this analysis because it would simply and cleanly display how qualities of songs, such as duration, have changed over time
  - I could calculate percentiles to determine what years place where as far as percentiles (ex: if several years in the 2010s placed in high percentiles, this would support my alternate hypothesis)
  - If I wnated to take large-scale, long-term approach to observing if songs have decreased in length over the decades, I could create a scatterplot measuring the correlation between the passing of time and shortening song duration
  - Based on my null hypothesis and alternate hypothesis, I would conduct a hypothesis test, and use the p-value and confidence interval to draw a conclusion about my data
  - I could perform an ANOVA test to determine if the difference in song length between decades or years is statistically significant, based on the f-value

```{r}
library(readr)
data <- read_csv("GitHub/jour405_spring25/project/data.csv")
View(data)
```

Notes:
  - This dataset contains over 160,000 songs released from 1921-2020 that were retrieved from the Spotify Web API
  - I downloaded this data as a CSV from Kaggle (https://www.kaggle.com/datasets/yamaerenay/spotify-dataset-1921-2020-160k-tracks?select=data.csv)
  - This dataset is an older, smaller version - there is an updated version with over 600,000 songs - but for the sake of working with a dataset under 100 MB, I chose to download this one
  - I'd also say 160,000 songs is a sufficient number for the purpose of my research
  - Columns of data include valence (positivity of the song's subject matter), accousticness (how accoustic a track is), danceability, energy, instrumentalness, liveness, loudness, etc.
  - Though the only columns that are applicable to my hypotheses are year and duration
  - The duration is unforunately in miliseconds, which is a bit inconvenient, but there may be a way to convert them into minutes + seconds or seconds (which I would likely need help with)
  - The dataset including songs from as long ago as 1921 is beneficial because it will allow me to recognize statistical trends over a larger period of time
  - The quantity of songs also makes the population larger
  - My original hypothesis regarded song lengths since 2019, though I will probably have to measure change in song length from a few years before that because this dataset only includes songs as recent as 2020
  - One year's worth of songs would probably not be enough for the purposes of my hypotheses
  _ I would likely change my hypothesis to 2010, just to measure how song lengths have changed before and after the rise of technology (and the modern era)
